#!/usr/bin/env bash
# Checking for command-line argument if its worked or not 
if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assigning the  Arguments to the given  variables

path_to_file=No 1
ip=no2
username=no3
path_to_ssh_key=no4


# Disabbling Strict the  Host Key checking
scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# Checking if the transfer was successful completed
if [ $? -eq 0 ]
then
  echo "FILE TRANSFER WAS SUCCESSFULL"
else
  echo "FILE TRANSFER FAILED"
fi
