#!/usr/bin/env bash
#Double the number of webservers
sudo apt update
sudo apt install haproxy -y
#sudo wget -q -O /etc/nginx/nginx.conf https://exampleconfig.com/static/raw/nginx/ubuntu20.04/etc/nginx/nginx.conf
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 102634-web-01 54.144.147.110:80 check\n\tserver server2  102634-web-02 35.153.79.54:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
