#!/usr/bin/env bash
#  a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distributes requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  TEMESGENABDISSA_frontend
        bind *:80
        mode http
        default_backend TEMESGENABDISSA_backend
backend TEMESGENABDISSA_backend
        balance roundrobin
        server 102634-web-01 54.144.147.110:80 check
        server 102634-web-02 35.153.79.54:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
